# config.py

RANDOM_SEED = 42

ENV_NUM_RELAYS = 500  
ENV_GUARD_FRACTION = 0.60
ENV_EXIT_FRACTION = 0.28

RELAY_MIN_BANDWIDTH = 0.5
RELAY_MAX_BANDWIDTH = 1000.0
RELAY_MIN_LATENCY = 5.0
RELAY_MAX_LATENCY = 300.0

RELAY_FAILURE_RATE = 0.05
RELAY_RECOVERY_RATE = 0.1

ENABLE_CONGESTION = True       
CONGESTION_VARIANCE = 0.2     

ENABLE_GUARD_ROTATION = True  
GUARD_ROTATION_INTERVAL = 500  

ENABLE_GEOGRAPHIC_DIVERSITY = True
NUM_GEOGRAPHIC_REGIONS = 10     
NUM_OPERATORS = 50             

REWARD_INVALID_ACTION = -10.0
REWARD_BANDWIDTH_WEIGHT = 15.0
REWARD_LATENCY_WEIGHT = -4.0
REWARD_DIVERSITY_WEIGHT = 10.0

ANONYMITY_HISTORY_SIZE = 100
EVAL_EPSILON = 0.90 

TRAIN_NUM_EPISODES = 20000
TRAIN_LOG_FREQ = 100

DQN_LEARNING_RATE = 0.0001
DQN_DISCOUNT_FACTOR = 0.99
DQN_EPSILON_START = 1.0
DQN_EPSILON_DECAY = 0.9995
DQN_EPSILON_MIN = 0.05
DQN_BATCH_SIZE = 128
DQN_MEMORY_SIZE = 10000
DQN_TARGET_UPDATE_FREQ = 50